### ISSUE TITLE
Add platform authentication

### ISSUE THREAD

**Issue by ziiw** [samouss/webauthn-experiments#3]
After the WWDC20 and [this video](https://developer.apple.com/videos/play/wwdc2020/10670/) I think that your project could get an upgrade with Face ID and Touch ID support.

The main point consist on adding a property to the `options` object: 
```javascript
const options = {
  publicKey: {
     authenticatorSelection: { authenticatorAttachment: "platform" }
  }
}

const publickeyCredential = await navigator.credentials.create(options)
```

Then in the back-end part there is also some work that needs to be done in order to validate the signature.

What do you think ?

**Comment by samouss** [comment]
Hi! I don't have macOS Big Sur, so I can't test with Safari. Touch ID x Webauthn [is only available on Big Sur](https://webkit.org/blog/10875/release-notes-for-safari-technology-preview-109-with-safari-14-features/) even with Safari Technology Preview. I guess that it should work as it does in Chrome (unless you've already tested). By default, the browser looks for both kinds of authenticator `platform` OR `cross-platform` because the field [`authenticatorAttachment`](https://www.w3.org/TR/webauthn/#attachment) is optional. The user is free to choose the option that suits him the most.
